### ISSUE TITLE
"Supplied By" title

### ISSUE THREAD

**Issue by embu18** [omarestrella/ember-emoji-one#4]
![Screenshot_2020-02-20_14-46-31](https://user-images.githubusercontent.com/46724214/74934664-c7a92500-53f7-11ea-9287-57a5d8232a69.png)
 Is it possible to get rid of the "Emoji Icons supplied by EmojiOne"? 
 Also if I understand correctly, the icon set is proprietary and in order to use it, we, as a commercial company, have to buy the license and only then can use this package, right?

**Comment by omarestrella** [comment]
EmojiOne has its own licensing requirements: https://github.com/joypixels/emojione#license-to-use-emojione-images

Attribution is required for free use. You can remove it with CSS, `display: none`, on that attribution element.

This library will be updated to use Twemoji soon, since the licensing requirements are simpler.
